REM INSERTING into PUBLIC.MUNICIPALITY
SET DEFINE OFF;
Insert into PUBLIC.MUNICIPALITY ("id_municipality","municipality_name","id_state_code") values ('1','Acatic','14');
Insert into PUBLIC.MUNICIPALITY ("id_municipality","municipality_name","id_state_code") values ('2','Acatlán de Juárez','14');
Insert into PUBLIC.MUNICIPALITY ("id_municipality","municipality_name","id_state_code") values ('3','Ahualulco de Mercado','14');
Insert into PUBLIC.MUNICIPALITY ("id_municipality","municipality_name","id_state_code") values ('4','Amacueca','14');
Insert into PUBLIC.MUNICIPALITY ("id_municipality","municipality_name","id_state_code") values ('5','Amatitán','14');
Insert into PUBLIC.MUNICIPALITY ("id_municipality","municipality_name","id_state_code") values ('6','Ameca','14');
Insert into PUBLIC.MUNICIPALITY ("id_municipality","municipality_name","id_state_code") values ('7','San Juanito de Escobedo','14');
Insert into PUBLIC.MUNICIPALITY ("id_municipality","municipality_name","id_state_code") values ('8','Arandas','14');
Insert into PUBLIC.MUNICIPALITY ("id_municipality","municipality_name","id_state_code") values ('9','El Arenal','14');
Insert into PUBLIC.MUNICIPALITY ("id_municipality","municipality_name","id_state_code") values ('10','Atemajac de Brizuela','14');
Insert into PUBLIC.MUNICIPALITY ("id_municipality","municipality_name","id_state_code") values ('11','Atengo','14');
Insert into PUBLIC.MUNICIPALITY ("id_municipality","municipality_name","id_state_code") values ('12','Atenguillo','14');
Insert into PUBLIC.MUNICIPALITY ("id_municipality","municipality_name","id_state_code") values ('13','Atotonilco el Alto','14');
Insert into PUBLIC.MUNICIPALITY ("id_municipality","municipality_name","id_state_code") values ('14','Atoyac','14');
Insert into PUBLIC.MUNICIPALITY ("id_municipality","municipality_name","id_state_code") values ('15','Autlán de Navarro','14');
Insert into PUBLIC.MUNICIPALITY ("id_municipality","municipality_name","id_state_code") values ('16','Ayotlán','14');
Insert into PUBLIC.MUNICIPALITY ("id_municipality","municipality_name","id_state_code") values ('17','Ayutla','14');
Insert into PUBLIC.MUNICIPALITY ("id_municipality","municipality_name","id_state_code") values ('18','La Barca','14');
Insert into PUBLIC.MUNICIPALITY ("id_municipality","municipality_name","id_state_code") values ('19','Bolaños','14');
Insert into PUBLIC.MUNICIPALITY ("id_municipality","municipality_name","id_state_code") values ('20','Cabo Corrientes','14');
Insert into PUBLIC.MUNICIPALITY ("id_municipality","municipality_name","id_state_code") values ('21','Casimiro Castillo','14');
Insert into PUBLIC.MUNICIPALITY ("id_municipality","municipality_name","id_state_code") values ('22','Cihuatlán','14');
Insert into PUBLIC.MUNICIPALITY ("id_municipality","municipality_name","id_state_code") values ('23','Zapotlán el Grande','14');
Insert into PUBLIC.MUNICIPALITY ("id_municipality","municipality_name","id_state_code") values ('24','Cocula','14');
Insert into PUBLIC.MUNICIPALITY ("id_municipality","municipality_name","id_state_code") values ('25','Colotlán','14');
Insert into PUBLIC.MUNICIPALITY ("id_municipality","municipality_name","id_state_code") values ('26','Concepción de Buenos Aires','14');
Insert into PUBLIC.MUNICIPALITY ("id_municipality","municipality_name","id_state_code") values ('27','Cuautitlán de García Barragán','14');
Insert into PUBLIC.MUNICIPALITY ("id_municipality","municipality_name","id_state_code") values ('28','Cuautla','14');
Insert into PUBLIC.MUNICIPALITY ("id_municipality","municipality_name","id_state_code") values ('29','Cuquío','14');
Insert into PUBLIC.MUNICIPALITY ("id_municipality","municipality_name","id_state_code") values ('30','Chapala','14');
Insert into PUBLIC.MUNICIPALITY ("id_municipality","municipality_name","id_state_code") values ('31','Chimaltitán','14');
Insert into PUBLIC.MUNICIPALITY ("id_municipality","municipality_name","id_state_code") values ('32','Chiquilistlán','14');
Insert into PUBLIC.MUNICIPALITY ("id_municipality","municipality_name","id_state_code") values ('33','Degollado','14');
Insert into PUBLIC.MUNICIPALITY ("id_municipality","municipality_name","id_state_code") values ('34','Ejutla','14');
Insert into PUBLIC.MUNICIPALITY ("id_municipality","municipality_name","id_state_code") values ('35','Encarnación de Díaz','14');
Insert into PUBLIC.MUNICIPALITY ("id_municipality","municipality_name","id_state_code") values ('36','Etzatlán','14');
Insert into PUBLIC.MUNICIPALITY ("id_municipality","municipality_name","id_state_code") values ('37','El Grullo','14');
Insert into PUBLIC.MUNICIPALITY ("id_municipality","municipality_name","id_state_code") values ('38','Guachinango','14');
Insert into PUBLIC.MUNICIPALITY ("id_municipality","municipality_name","id_state_code") values ('39','Guadalajara','14');
Insert into PUBLIC.MUNICIPALITY ("id_municipality","municipality_name","id_state_code") values ('40','Hostotipaquillo','14');
Insert into PUBLIC.MUNICIPALITY ("id_municipality","municipality_name","id_state_code") values ('41','Huejúcar','14');
Insert into PUBLIC.MUNICIPALITY ("id_municipality","municipality_name","id_state_code") values ('42','Huejuquilla el Alto','14');
Insert into PUBLIC.MUNICIPALITY ("id_municipality","municipality_name","id_state_code") values ('43','La Huerta','14');
Insert into PUBLIC.MUNICIPALITY ("id_municipality","municipality_name","id_state_code") values ('44','Ixtlahuacán de los Membrillos','14');
Insert into PUBLIC.MUNICIPALITY ("id_municipality","municipality_name","id_state_code") values ('45','Ixtlahuacán del Río','14');
Insert into PUBLIC.MUNICIPALITY ("id_municipality","municipality_name","id_state_code") values ('46','Jalostotitlán','14');
Insert into PUBLIC.MUNICIPALITY ("id_municipality","municipality_name","id_state_code") values ('47','Jamay','14');
Insert into PUBLIC.MUNICIPALITY ("id_municipality","municipality_name","id_state_code") values ('48','Jesús María','14');
Insert into PUBLIC.MUNICIPALITY ("id_municipality","municipality_name","id_state_code") values ('49','Jilotlán de los Dolores','14');
Insert into PUBLIC.MUNICIPALITY ("id_municipality","municipality_name","id_state_code") values ('50','Jocotepec','14');
Insert into PUBLIC.MUNICIPALITY ("id_municipality","municipality_name","id_state_code") values ('51','Juanacatlán','14');
Insert into PUBLIC.MUNICIPALITY ("id_municipality","municipality_name","id_state_code") values ('52','Juchitlán','14');
Insert into PUBLIC.MUNICIPALITY ("id_municipality","municipality_name","id_state_code") values ('53','Lagos de Moreno','14');
Insert into PUBLIC.MUNICIPALITY ("id_municipality","municipality_name","id_state_code") values ('54','El Limón','14');
Insert into PUBLIC.MUNICIPALITY ("id_municipality","municipality_name","id_state_code") values ('55','Magdalena','14');
Insert into PUBLIC.MUNICIPALITY ("id_municipality","municipality_name","id_state_code") values ('56','Santa María del Oro','14');
Insert into PUBLIC.MUNICIPALITY ("id_municipality","municipality_name","id_state_code") values ('57','La Manzanilla de la Paz','14');
Insert into PUBLIC.MUNICIPALITY ("id_municipality","municipality_name","id_state_code") values ('58','Mascota','14');
Insert into PUBLIC.MUNICIPALITY ("id_municipality","municipality_name","id_state_code") values ('59','Mazamitla','14');
Insert into PUBLIC.MUNICIPALITY ("id_municipality","municipality_name","id_state_code") values ('60','Mexticacán','14');
Insert into PUBLIC.MUNICIPALITY ("id_municipality","municipality_name","id_state_code") values ('61','Mezquitic','14');
Insert into PUBLIC.MUNICIPALITY ("id_municipality","municipality_name","id_state_code") values ('62','Mixtlán','14');
Insert into PUBLIC.MUNICIPALITY ("id_municipality","municipality_name","id_state_code") values ('63','Ocotlán','14');
Insert into PUBLIC.MUNICIPALITY ("id_municipality","municipality_name","id_state_code") values ('64','Ojuelos de Jalisco','14');
Insert into PUBLIC.MUNICIPALITY ("id_municipality","municipality_name","id_state_code") values ('65','Pihuamo','14');
Insert into PUBLIC.MUNICIPALITY ("id_municipality","municipality_name","id_state_code") values ('66','Poncitlán','14');
Insert into PUBLIC.MUNICIPALITY ("id_municipality","municipality_name","id_state_code") values ('67','Puerto Vallarta','14');
Insert into PUBLIC.MUNICIPALITY ("id_municipality","municipality_name","id_state_code") values ('68','Villa Purificación','14');
Insert into PUBLIC.MUNICIPALITY ("id_municipality","municipality_name","id_state_code") values ('69','Quitupan','14');
Insert into PUBLIC.MUNICIPALITY ("id_municipality","municipality_name","id_state_code") values ('70','El Salto','14');
Insert into PUBLIC.MUNICIPALITY ("id_municipality","municipality_name","id_state_code") values ('71','San Cristóbal de la Barranca','14');
Insert into PUBLIC.MUNICIPALITY ("id_municipality","municipality_name","id_state_code") values ('72','San Diego de Alejandría','14');
Insert into PUBLIC.MUNICIPALITY ("id_municipality","municipality_name","id_state_code") values ('73','San Juan de los Lagos','14');
Insert into PUBLIC.MUNICIPALITY ("id_municipality","municipality_name","id_state_code") values ('74','San Julián','14');
Insert into PUBLIC.MUNICIPALITY ("id_municipality","municipality_name","id_state_code") values ('75','San Marcos','14');
Insert into PUBLIC.MUNICIPALITY ("id_municipality","municipality_name","id_state_code") values ('76','San Martín de Bolaños','14');
Insert into PUBLIC.MUNICIPALITY ("id_municipality","municipality_name","id_state_code") values ('77','San Martín Hidalgo','14');
Insert into PUBLIC.MUNICIPALITY ("id_municipality","municipality_name","id_state_code") values ('78','San Miguel el Alto','14');
Insert into PUBLIC.MUNICIPALITY ("id_municipality","municipality_name","id_state_code") values ('79','Gómez Farías','14');
Insert into PUBLIC.MUNICIPALITY ("id_municipality","municipality_name","id_state_code") values ('80','San Sebastián del Oeste		','14');
Insert into PUBLIC.MUNICIPALITY ("id_municipality","municipality_name","id_state_code") values ('81','Santa María de los Ángeles','14');
Insert into PUBLIC.MUNICIPALITY ("id_municipality","municipality_name","id_state_code") values ('82','Sayula','14');
Insert into PUBLIC.MUNICIPALITY ("id_municipality","municipality_name","id_state_code") values ('83','Tala','14');
Insert into PUBLIC.MUNICIPALITY ("id_municipality","municipality_name","id_state_code") values ('84','Talpa de Allende','14');
Insert into PUBLIC.MUNICIPALITY ("id_municipality","municipality_name","id_state_code") values ('85','Tamazula de Gordiano','14');
Insert into PUBLIC.MUNICIPALITY ("id_municipality","municipality_name","id_state_code") values ('86','Tapalpa','14');
Insert into PUBLIC.MUNICIPALITY ("id_municipality","municipality_name","id_state_code") values ('87','Tecalitlán','14');
Insert into PUBLIC.MUNICIPALITY ("id_municipality","municipality_name","id_state_code") values ('88','Techaluta de Montenegro','14');
Insert into PUBLIC.MUNICIPALITY ("id_municipality","municipality_name","id_state_code") values ('89','Tecolotlán','14');
Insert into PUBLIC.MUNICIPALITY ("id_municipality","municipality_name","id_state_code") values ('90','Tenamaxtlán','14');
Insert into PUBLIC.MUNICIPALITY ("id_municipality","municipality_name","id_state_code") values ('91','Teocaltiche','14');
Insert into PUBLIC.MUNICIPALITY ("id_municipality","municipality_name","id_state_code") values ('92','Teocuitatlán de Corona','14');
Insert into PUBLIC.MUNICIPALITY ("id_municipality","municipality_name","id_state_code") values ('93','Tepatitlán de Morelos','14');
Insert into PUBLIC.MUNICIPALITY ("id_municipality","municipality_name","id_state_code") values ('94','Tequila','14');
Insert into PUBLIC.MUNICIPALITY ("id_municipality","municipality_name","id_state_code") values ('95','Teuchitlán','14');
Insert into PUBLIC.MUNICIPALITY ("id_municipality","municipality_name","id_state_code") values ('96','Tizapán el Alto','14');
Insert into PUBLIC.MUNICIPALITY ("id_municipality","municipality_name","id_state_code") values ('97','Tlajomulco de Zúñiga','14');
Insert into PUBLIC.MUNICIPALITY ("id_municipality","municipality_name","id_state_code") values ('98','Tlaquepaque','14');
Insert into PUBLIC.MUNICIPALITY ("id_municipality","municipality_name","id_state_code") values ('99','Tolimán','14');
Insert into PUBLIC.MUNICIPALITY ("id_municipality","municipality_name","id_state_code") values ('100','Tomatlán','14');
Insert into PUBLIC.MUNICIPALITY ("id_municipality","municipality_name","id_state_code") values ('101','Tonalá','14');
Insert into PUBLIC.MUNICIPALITY ("id_municipality","municipality_name","id_state_code") values ('102','Tonaya','14');
Insert into PUBLIC.MUNICIPALITY ("id_municipality","municipality_name","id_state_code") values ('103','Tonila','14');
Insert into PUBLIC.MUNICIPALITY ("id_municipality","municipality_name","id_state_code") values ('104','Totatiche','14');
Insert into PUBLIC.MUNICIPALITY ("id_municipality","municipality_name","id_state_code") values ('105','Tototlán','14');
Insert into PUBLIC.MUNICIPALITY ("id_municipality","municipality_name","id_state_code") values ('106','Tuxcacuesco','14');
Insert into PUBLIC.MUNICIPALITY ("id_municipality","municipality_name","id_state_code") values ('107','Tuxcueca','14');
Insert into PUBLIC.MUNICIPALITY ("id_municipality","municipality_name","id_state_code") values ('108','Tuxpan','14');
Insert into PUBLIC.MUNICIPALITY ("id_municipality","municipality_name","id_state_code") values ('109','Unión de San Antonio','14');
Insert into PUBLIC.MUNICIPALITY ("id_municipality","municipality_name","id_state_code") values ('110','Unión de Tula','14');
Insert into PUBLIC.MUNICIPALITY ("id_municipality","municipality_name","id_state_code") values ('111','Valle de Guadalupe','14');
Insert into PUBLIC.MUNICIPALITY ("id_municipality","municipality_name","id_state_code") values ('112','Valle de Juárez','14');
Insert into PUBLIC.MUNICIPALITY ("id_municipality","municipality_name","id_state_code") values ('113','San Gabriel','14');
Insert into PUBLIC.MUNICIPALITY ("id_municipality","municipality_name","id_state_code") values ('114','Villa Corona','14');
Insert into PUBLIC.MUNICIPALITY ("id_municipality","municipality_name","id_state_code") values ('115','Villa Guerrero','14');
Insert into PUBLIC.MUNICIPALITY ("id_municipality","municipality_name","id_state_code") values ('116','Villa Hidalgo','14');
Insert into PUBLIC.MUNICIPALITY ("id_municipality","municipality_name","id_state_code") values ('117','Cañadas de Obregón','14');
Insert into PUBLIC.MUNICIPALITY ("id_municipality","municipality_name","id_state_code") values ('118','Yahualica de González Gallo','14');
Insert into PUBLIC.MUNICIPALITY ("id_municipality","municipality_name","id_state_code") values ('119','Zacoalco de Torres','14');
Insert into PUBLIC.MUNICIPALITY ("id_municipality","municipality_name","id_state_code") values ('120','Zapopan','14');
Insert into PUBLIC.MUNICIPALITY ("id_municipality","municipality_name","id_state_code") values ('121','Zapotiltic','14');
Insert into PUBLIC.MUNICIPALITY ("id_municipality","municipality_name","id_state_code") values ('122','Zapotitlán de Vadillo','14');
Insert into PUBLIC.MUNICIPALITY ("id_municipality","municipality_name","id_state_code") values ('123','Zapotlán del Rey','14');
Insert into PUBLIC.MUNICIPALITY ("id_municipality","municipality_name","id_state_code") values ('124','Zapotlanejo','14');
Insert into PUBLIC.MUNICIPALITY ("id_municipality","municipality_name","id_state_code") values ('125','San Ignacio Cerro Gordo','14');
COMMIT;


SELECT * FROM public.MUNICIPALITY;
